# Generated by Django 4.1.2 on 2022-10-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name="TO'LIQ ISM")),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=5, verbose_name='BALL')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name="QO'SHILGAN VAQTI")),
            ],
            options={
                'verbose_name': 'Telegram obunachilar',
                'verbose_name_plural': 'Telegram obunachilar',
            },
        ),
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='competition.telegramusers', verbose_name='Taklif qilingan')),
                ('user_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='competition.telegramusers', verbose_name='Taklif qilgan')),
            ],
            options={
                'verbose_name': 'Taklif qilingan obunachilar',
                'verbose_name_plural': 'Taklif qilingan obunachilar',
            },
        ),
    ]
